const List<String> universities = [
  'Centro Universitário Católica de Santa Catarina – Católica SC',
  'Centro Universitário da FEI – Universidade FEI',
  'Centro Universitário de Belo Horizonte – UNI-BH',
  'Centro Universitário de Brasília – UNICEUB',
  'Centro Universitário do Pará – CESUPA',
  'Centro Universitário FEI – FEI',
  'Centro Universitário Newton Paiva – Newton Paiva',
  'Pontifícia Universidade Católica de Campinas – PUC-Campinas',
  'Pontifícia Universidade Católica de Minas Gerais – PUC-MG',
  'Pontifícia Universidade Católica de São Paulo – PUC-SP',
  'Pontifícia Universidade Católica do Rio de Janeiro – PUC-RJ',
  'Pontifícia Universidade Católica do Rio Grande do Sul – PUC-RS',
  'Universidade Anhembi Morumbi – UAM',
  'Universidade Castelo Branco – UCB',
  'Universidade Cidade de São Paulo – UNICID',
  'Universidade de Brasília – UnB',
  'Universidade de Caxias do Sul – UCS',
  'Universidade de Fortaleza – UNIFOR',
  'Universidade de Franca – UNIFRAN',
  'Universidade de Mogi das Cruzes – UMC',
  'Universidade de Passo Fundo – UPF',
  'Universidade de Santo Amaro – UNISA',
  'Universidade de São Paulo – USP',
  'Universidade do Estado da Bahia – UNEB',
  'Universidade do Estado de Santa Catarina – UDESC',
  'Universidade do Sul de Santa Catarina – UNISUL',
  'Universidade do Vale do Paraíba – UNIVAP',
  'Universidade do Vale do Rio dos Sinos – UNISINOS',
  'Universidade Estadual de Campinas – UNICAMP',
  'Universidade Estadual de Campinas — Faculdade de Tecnologia – UNICAMP-FT',
  'Universidade Estadual de Feira de Santana – UEFS',
  'Universidade Estadual de Goiás – UEG',
  'Universidade Estadual de Londrina – UEL',
  'Universidade Estadual de Maringá – UEM',
  'Universidade Estadual de Montes Claros – UNIMONTES',
  'Universidade Estadual de Ponta Grossa – UEPG',
  'Universidade Estadual de Roraima – UERR',
  'Universidade Estadual de Santa Cruz – UESC',
  'Universidade Estadual de Santa Maria – UFSM',
  'Universidade Estadual do Norte Fluminense – UENF',
  'Universidade Estadual do Oeste do Paraná – UNIOESTE',
  'Universidade Estadual do Rio de Janeiro – UERJ',
  'Universidade Estadual do Sudoeste da Bahia – UESB',
  'Universidade Estadual Paulista Júlio de Mesquita Filho – UNESP',
  'Universidade Estadual Paulista — Campus de Ribeirão Preto – UNESP-RP',
  'Universidade Federal da Bahia – UFBA',
  'Universidade Federal da Fronteira Sul – UFFS',
  'Universidade Federal da Grande Dourados – UFGD',
  'Universidade Federal da Integração Latino-Americana – UNILA',
  'Universidade Federal de Alagoas – UFAL / UFAlagoas',
  'Universidade Federal de Alfenas – UNIFAL-MG',
  'Universidade Federal de Campina Grande – UFCG',
  'Universidade Federal de Ciências da Saúde de Porto Alegre – UFCSPA',
  'Universidade Federal de Goiás – UFG',
  'Universidade Federal de Itajubá – UNIFEI',
  'Universidade Federal de Juiz de Fora – UFJF',
  'Universidade Federal de Lavras – UFLA',
  'Universidade Federal de Mato Grosso – UFMT',
  'Universidade Federal de Mato Grosso do Sul – UFMS',
  'Universidade Federal de Minas Gerais – UFMG',
  'Universidade Federal de Ouro Preto – UFOP',
  'Universidade Federal de Pernambuco – UFPE',
  'Universidade Federal de Rondônia – UNIR',
  'Universidade Federal de Roraima – UFRR',
  'Universidade Federal de São Carlos – UFSCar',
  'Universidade Federal de São João del-Rei – UFSJ',
  'Universidade Federal de São Paulo – UNIFESP',
  'Universidade Federal de Sergipe – UFS',
  'Universidade Federal de Tocantins – UFT',
  'Universidade Federal de Uberlândia – UFU',
  'Universidade Federal de Viçosa – UFV',
  'Universidade Federal do ABC – UFABC',
  'Universidade Federal do Acre – UFAC',
  'Universidade Federal do Amazonas – UFAM',
  'Universidade Federal do Cariri – UFCA',
  'Universidade Federal do Ceará – UFC',
  'Universidade Federal do Paraná – UFPR',
  'Universidade Federal do Pará – UFPA',
  'Universidade Federal do Piauí – UFPI',
  'Universidade Federal do Recôncavo da Bahia – UFRB',
  'Universidade Federal do Rio de Janeiro – UFRJ',
  'Universidade Federal do Rio Grande do Norte – UFRN',
  'Universidade Federal do Rio Grande do Sul – UFRGS',
  'Universidade Federal do Sul e Sudeste do Pará – UNIFESSPA',
  'Universidade Federal do Oeste do Pará – UFOPA',
  'Universidade Federal Rural de Pernambuco – UFRPE',
  'Universidade Federal Rural do Rio de Janeiro – UFRRJ',
  'Universidade Federal Rural do Semi-Árido – UFERSA',
  'Universidade Metodista de São Paulo – UMESP',
  'Universidade Paulista – UNIP',
  'Universidade Presbiteriana Mackenzie – Mackenzie',
  'Universidade Regional do Cariri – URCA',
  'Universidade São Judas Tadeu – USJT',
];
